require:
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

RSpec/FilePath:
  CustomTransform:
    GraphQL: graphql

Gemspec/RequireMFA:
  Enabled: false
