require:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

RSpec/FilePath:
  CustomTransform:
    GraphQL: graphql

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false
