inherit_gem:
  rubocop-basic: rubocop.yml

plugins:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

RSpec/SpecFilePathFormat:
  CustomTransform:
    GraphQL: graphql
