version: 2.1
orbs:
  ruby: circleci/ruby@2.1.0

commands:
  codeclimate:
    steps:
      - run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-$CC_TEST_REPORTER_VERSION > ./cc
          chmod +x ./cc
          ./cc format-coverage -t simplecov coverage/coverage.json
          ./cc upload-coverage
          rm ./cc

executors:
  default:
    parameters:
      ruby-version:
        description: "ruby version tag"
        default: "3.4.1"
        type: string
      postgres-version:
        description: "postgres version tag"
        default: "17.0"
        type: string
    docker:
      - image: cimg/ruby:<<parameters.ruby-version>>
      - image: cimg/postgres:<<parameters.postgres-version>>
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: dummy_test
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      CI: enabled
      RAILS_ENV: test
      RACK_ENV: test
      PGHOST: localhost

jobs:
  rspec:
    parameters:
      ruby-version:
        description: "ruby version tag"
        type: string
    executor:
      name: default
      ruby-version: <<parameters.ruby-version>>
    steps:
      - checkout
      - ruby/install-deps
      - run: dockerize -wait tcp://localhost:5432 -timeout 2m
      - run: bundle exec rake -f spec/dummy/Rakefile db:schema:load
      - ruby/rspec-test
      - codeclimate
  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check
  release:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rake release
  yard:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec yard doc

workflows:
  version: 2.1
  build:
    jobs:
      - rspec:
          matrix:
            parameters:
              ruby-version:
                - "3.4.1"
                - "3.3.7"
                - "3.2.6"
      - rubocop
      - yard
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
