version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0

executors:
  default:
    docker:
      - image: cimg/ruby:3.1.2
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: dummy_test
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      RAILS_ENV: test
      RACK_ENV: test
      PGHOST: localhost

jobs:
  rspec:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: dockerize -wait tcp://localhost:5432 -timeout 2m
      - run: cd spec/dummy && rake db:schema:load
      - ruby/rspec-test
  rubocop:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check
  release:
    executor: default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rake release

workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      - rubocop
      - release:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          requires:
            - rspec
            - rubocop
